# Makefile for FriendsRender

Friends : Intersect.cpp LightSampler.cpp main.cpp Matrix.cpp Normal_Facet.cpp Quaternion.cpp RayUtility.cpp Sampling.cpp Scene.cpp SPPM.cpp stb_image.cpp stb_image_write.cpp TextureUtility.cpp tiny_obj_loader.cpp Vec.cpp
	g++ -O2 -o FriendsRender_R \
	Intersect.cpp \
	LightSampler.cpp \
	main.cpp \
	Matrix.cpp \
	Normal_Facet.cpp \
	Quaternion.cpp \
	RayUtility.cpp \
	Sampling.cpp \
	Scene.cpp \
	SPPM.cpp \
	stb_image.cpp \
	stb_image_write.cpp \
	TextureUtility.cpp \
	tiny_obj_loader.cpp \
	Vec.cpp \
	-std=c++17 -ffast-math -Ofast -mavx -fopenmp

